### ISSUE TITLE
嗨！请问你的滑动验证没有后端的支持吗

### ISSUE THREAD

**Issue by swarm413** [mikexfreeze/slide-verify#10]
亲爱的朋友：
你好！昨天在npm搜索到了你的简明滑动验证码，做的非常出色。但是一个疑惑始终在我心中久久不去，这个滑动验证码实际上是前端的产物，换句话说：即便是将这个验证码加入到登陆注册界面，仍然能够绕过验证码向服务端发送请求，比如说用postman不断向服务端接口发送请求。那么，验证码的实际目的不就已经失效了吗？
希望能及时收到你的回复。
                                                                                                                                                                                       Swarm413
                                                                                                                                                                                       2020/04/09

**Comment by mikexfreeze** [comment]
> 亲爱的朋友：
> 你好！昨天在npm搜索到了你的简明滑动验证码，做的非常出色。但是一个疑惑始终在我心中久久不去，这个滑动验证码实际上是前端的产物，换句话说：即便是将这个验证码加入到登陆注册界面，仍然能够绕过验证码向服务端发送请求，比如说用postman不断向服务端接口发送请求。那么，验证码的实际目的不就已经失效了吗？
> 希望能及时收到你的回复。
> Swarm413
> 2020/04/09

抱歉，回复的很迟。您说的问题确实存在，直接发送请求完全可以绕过验证。为了加强安全性，我觉得更安全的方法是在请求中加入前端生成的 token。在滑动验证完成后用 JS 生成一段 token 发送给后端用于第一次的登录验证。用于加盐的原始字段隐藏在已经编译过的代码中，第三方要想找出几乎是不可能的。
