### ISSUE TITLE
嗨！这款滑动验证码似乎不支持移动端验证

### ISSUE THREAD

**Issue by swarm413** [mikexfreeze/slide-verify#11]
亲爱的朋友：
你好！这款滑动验证码能在PC端很好的运行

![无标题123](https://user-images.githubusercontent.com/60997350/114120944-18dbe700-9920-11eb-9d0b-75ad1e9f05bc.png)
 
令人遗憾的是，似乎在移动端，这款验证码的表现就差强人意了
![无标题456](https://user-images.githubusercontent.com/60997350/114121275-a7506880-9920-11eb-80fb-582ac190fc35.png)

希望能及时收到你的回复
Swarm413
2021/04/09

**Comment by mikexfreeze** [comment]
感谢反馈，我尽快修复。

**Comment by mikexfreeze** [comment]
已修复，1.0.2 请尝试
