### ISSUE TITLE
大哥，组件宽高设不了啊，没有对外暴露

### ISSUE THREAD

**Issue by tianyazjq** [mikexfreeze/slide-verify#4]
大哥，组件宽高设不了啊，没有对外暴露

**Comment by mikexfreeze** [comment]
可以描述下需求场景嘛，需要设置成多宽多高，这个算是 feature 了。

**Comment by tianyazjq** [comment]
> 可以描述下需求场景嘛，需要设置成多宽多高，这个算是 feature 了。

那个在使用的过程中，发现图片太大了，想弄小都没有办法，这个看能不能把设置图片的width,height,暴露到options上面，不设使用默认的大小就好。

**Comment by mikexfreeze** [comment]
> > 可以描述下需求场景嘛，需要设置成多宽多高，这个算是 feature 了。
> 
> 那个在使用的过程中，发现图片太大了，想弄小都没有办法，这个看能不能把设置图片的width,height,暴露到options上面，不设使用默认的大小就好。

新增 source 参数使用举例
```
const Slide = new SlideVerify({
  elementId: "root",
  onSuccess: () => {console.log("success")},
  onFail: () => {console.log("fail")},
  onRefresh: () => {console.log("refresh")},
  photo: 'https://image.shutterstock.com/z/stock-photo-christmas-tree-ice-cream-winter-holiday-concept-736119322.jpg',
  source: [0, 0, 1000, 600]
})
```
`[x, y, width, height]` 仅在设置 photo 之后生效，截取给定图片。x, y 设置截取的横纵坐标起始点，width, height 设置截取的宽度和高度
